# Generated by Django 5.0 on 2023-12-10 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_messagemail'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogsMail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_try', models.DateTimeField(blank=True, null=True, verbose_name='последняя попытка')),
                ('status_try', models.CharField(blank=True, max_length=25, null=True, verbose_name='статус попытки')),
                ('response', models.TextField(blank=True, null=True, verbose_name='ответ сервера')),
                ('mail_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing.settingsmail', verbose_name='рассылка')),
            ],
            options={
                'verbose_name': 'Лог',
                'verbose_name_plural': 'Логи',
            },
        ),
    ]
