# Generated by Django 5.0 on 2023-12-11 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0004_alter_settingsmail_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logsmail',
            name='mail_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mailing.settingsmail', verbose_name='рассылка'),
        ),
        migrations.AlterField(
            model_name='messagemail',
            name='mail_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mailing.settingsmail', verbose_name='рассылка'),
        ),
        migrations.AlterField(
            model_name='settingsmail',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mailing.client', verbose_name='владелец'),
        ),
    ]
